### ISSUE TITLE
UI issue when having a /viewport set

### ISSUE THREAD

**Issue by xowis** [brainiac/MQ2Nav#1]
The UI window is not usable when having /viewport set. Text disappears as you move the window around the screen.  Mouse position is offset.

Disabling viewport with /viewport reset makes the UI look correct and function correctly.

![viewport ui issue](https://cloud.githubusercontent.com/assets/2627021/17237938/ef63fdbe-551c-11e6-94a2-0f001205ac21.png)

**Comment by xowis** [comment]
I figured it out and submitted a PR with the fix.

**Comment by brainiac** [comment]
Fixed via #2
