### ISSUE TITLE
Next:  Navigation via map integration is different from Live

### ISSUE THREAD

**Issue by Knightly1** [brainiac/MQ2Nav#101]
The coordinates given from an MQ2Nav map click do not allow for navigation.  This is particularly obvious in the Plane of Knowledge.  In testing, by issuing the commands manually, you can navigate CLOSE to the coordinates of specific areas, but not to those coordinates.

Using the same mesh files in Live, the same navigation via the map works fine.

**Comment by brainiac** [comment]
'twas a bug in mq2map passing the wrong coordinates.
