### ISSUE TITLE
Cannot completely load solution file from MQ2Nav-1.2.0.113

### ISSUE THREAD

**Issue by jessebevil** [brainiac/MQ2Nav#12]
Note required I convert solution as you are using a different version of VS than me. I'm using the following
Microsoft Visual Studio Community 2017 
Version 15.1 (26403.7) Release
VisualStudio.15.Release/15.1.0+26403.7
Microsoft .NET Framework
Version 4.6.01586

Installed Version: Community

Visual Basic 2017   00369-60000-00001-AA332
Microsoft Visual Basic 2017

Visual C# 2017   00369-60000-00001-AA332
Microsoft Visual C# 2017

Visual C++ 2017   00369-60000-00001-AA332
Microsoft Visual C++ 2017

ASP.NET and Web Tools 2017   15.0.30320.0
ASP.NET and Web Tools 2017

JavaScript Language Service   2.0
JavaScript Language Service

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

Visual Studio tools for CMake   1.0
Visual Studio tools for CMake

Visual Studio Tools for Unity   3.1.0.0
Visual Studio Tools for Unity

C:\MacroQuest2\MQ2Nav-1.2.0.113 (1)\MQ2Nav-1.2.0.113\plugin\MQ2Nav.vcxproj : error  : Unable to read the project file "MQ2Nav.vcxproj".
C:\MacroQuest2\MQ2Nav-1.2.0.113 (1)\MQ2Nav-1.2.0.113\plugin\MQ2Nav.vcxproj(38,5): The imported project "C:\MacroQuest2\MQ2Nav-1.2.0.113 (1)\Plugin.Debug.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.

Since this appears out of date and I'm impatient I figured I'd take a gander at the solution. MQ2Nav (Load Failed) populates when opening the solution. 

#include "common/proto/NavMeshFile.pb.h" errors saying cannot open source file. 

static void ToProto(nav::vector3& out_proto, const glm::vec3& v3) nav::vector3& shows namespace nav has no member vector3 - possibly related to previous errors?? Not really sure. Source not usable in it's current state for me as I'm uneducated in the ways of c. I just do macros and java atm. - MMOBugs::Chatwiththisname
![solution issue](https://user-images.githubusercontent.com/4873713/27513818-ef2430ee-593a-11e7-83f2-1e93359d182a.png)

**Comment by brainiac** [comment]
Apologies for the late response, I hadn't seen this until now (been super busy).

You need to put the MQ2Nav sources such that you have something that resembles the following:
C:\MacroQuest2\MQ2Nav\MQ2Nav.sln
C:\MacroQuest2\MQ2Main\MQ2Main.vcxproj

It relies on locating files in the MQ2 source so it needs to be lined up properly

**Comment by jessebevil** [comment]
Thanks for the response. I haven't checked but that certainly sounds like it will sort my issues out.
