### ISSUE TITLE
${Navigation.PathExists[target]} returns true when there is no path

### ISSUE THREAD

**Issue by remoteBranch** [brainiac/MQ2Nav#48]
I am seeing pathExists return true when I believe it should not. In the case I am showing below, I am standing in a valid and otherwise navigable mesh, and my destination point is also on a valid mesh. However there is no valid path between the two. Rather than returning FALSE, it is choosing an impossible route (in this case the straight line from where I am to where I have asked to be, through a wall). Further, because the invalid path it has chosen is unusually short, my algorithm is choosing this destination because it has the lowest cost, versus other, better options. 

There are a few examples of this in the game, below is a simple case from Crescent Reach. In this case the destination tunnel cannot be reached because of how I have generated the mesh. While I can solve this particular issue with the meshgenerator, I think the underlying problem is a bug.

I cannot tell from issue #41 if this behavior should also occur even when the start/end are not vertical. There is a z-axis delta in my example, but they are in different parts of the map. 

![capture](https://user-images.githubusercontent.com/3086946/50555407-a59f9100-0c91-11e9-9007-d9ca0d9ae444.JPG)

**Comment by brainiac** [comment]
Thank you for the detailed report. I think this is the same as #42. 

This is the behavior I expect to see with the current implementation. It’s basicslly resolving a path to the closest accessible point in terms of raw distance
