### ISSUE TITLE
Support distance argument in navigation commands

### ISSUE THREAD

**Issue by brainiac** [brainiac/MQ2Nav#53]
Current navigation commands are positional arguments. Add keyword argument support, and start with the distance command.

Example:

/nav target distance=30

Will navigate to within 30 units of the target

**Comment by jessebevil** [comment]
This please. I've been considering adding the use of Moveutils for ease of use at a target encounter, but this could alleviate the need. Though stick like behavior may still be needed for my plugin, at least my toon won't try to path to right on top of the npc.
