### ISSUE TITLE
Exception Unhandled RenderHandler::InvalidateDeviceObjects()

### ISSUE THREAD

**Issue by jessebevil** [brainiac/MQ2Nav#62]
So I crashed MQ2 during development of MQ2Farm more times than I care to admit. However, When I have a debugger attached most times it points at nav when I know that not to be the case. I have to unload MQ2Nav and bypass my mesh check to cause the crash again so that I can get it to point at my actual bug. 

Hopefully the below pasted image is available to see here. In this particular case I did get pointed at the issue with my plugin, then I hit continue, which pointed at the below. Not sure if this has been corrected in the existing updates, I didn't see it mentioned in the closed issues. 

![image](https://user-images.githubusercontent.com/4873713/51437140-888e2a80-1c5f-11e9-8b6e-19651f759e2d.png)

**Comment by brainiac** [comment]
Its related to #36 but should be fixed in develop branch already.
