### ISSUE TITLE
PathExists suddenly returning true with no path

### ISSUE THREAD

**Issue by Joojoobee-JJB** [brainiac/MQ2Nav#75]
PathExists returning True in scripts where before it did not (and should not).  Repeatable.  Wending ways.  Target a portal across the pit

/doortarget 25
/echo (${Navigation.PathExists[locxyz ${Switch.X} ${Switch.Y} ${Switch.Z}]})

returns true, when previously it always returns False (as it should)

I can provide my navmesh file as needed, but it's the same navmesh file as I've used for a couple of months...  so something recently has changed.

**Comment by brainiac** [comment]
Are you using 1.3.0 beta or not? Also use `/nav door` to save you some accuracy

**Comment by Joojoobee-JJB** [comment]
I am using whatever is in EQMule's recent update.  I would love to use your 1.3..0 Beta, but since this is for a public macro, I am trying to use the standard MQ2Nav.

But it doesn't matter whether I use Switch.X/Y/Z or just a simple "hard" XYZ location I measured by hand...  like this:

**/echo ${Navigation.PathExists[-250.66 446.92 22.41]}**

**It still reports PathExists to locations that there is no path.**  The only thing that is different is the MQ2 update...  so something changed.  A macro that worked the day before yesterday doesn't work now.

Can something in MQ2 change that "break" how MQ2 reports PathExists?

Thanks for your feedback!

JJB

PS-- Later tonight when I get home from work I will try the 1.3.0 beta to see if the problem extends to that.

**Comment by brainiac** [comment]
The issue is solved in the 1.3.0 beta. You can find a link to it in the releases page on github
