### ISSUE TITLE
MQ2Nav clicking certain Zone-Ports when within ~50 units

### ISSUE THREAD

**Issue by BDeakins** [brainiac/MQ2Nav#90]
MQ2Nav will automatically click certain zone-doors if MQ2Nav is loaded and the player passes near. 
 Can repro issue in Brell's Rest and in Field of Scale (SoD) with Kurn's Tower.

Start at Brell's Temple zone-door and attempt to nav to Underquarry.  You'll pass close to the Kernagir, The Shining City's zone-door (Port Object, whatever you want to call it).

You CANNOT nav past it without zoning into Kernagir.  If you /nav out of Kernagir, you cannot continue on to Underquarry without rezoning into Kernagir on an endless loop.

Start at 592 42 180, and run this macro:

```#warning
Sub Main

|- Brell's Rest
/echo We need to start near Brell's Temple door.
/while (${Zone.ShortName.Equal[brellsrest]}) {
    /echo Heading to \agThe Underquarry
    /call cancelLev
    /nav setopt log=debug
    /nav loc -1230 -675 -8
    /while (${Zone.ShortName.Equal[brellsrest]}) {
        /delay 5
    }
}

/while (${Zone.ShortName.Equal[shiningcity]}) {
    /echo How'd we end up here if MQ2Nav didn't click a door?
    /endm
}
/return

Sub cancelLev
    /if (!${Me.Levitating}) /return
    /declare intBuffSlot int local 1
    /declare intSDBuffSlot int local 1

    /for intBuffSlot 0 to 42
        /if (${Me.Buff[${intBuffSlot}].HasSPA[57]}) {
                /echo \ayRemoving buff #${intBuffSlot}: \am ${Me.Buff[${intBuffSlot}]}
            /removebuff "${Me.Buff[${intBuffSlot}]}"
            /delay 2s !${Me.Buff[${intBuffSlot}].ID}
        }
    /next intBuffSlot
    /for intSDBuffSlot 0 to 30
        /if (${Me.Song[${intSDBuffSlot}].HasSPA[57]})  {
                /echo \ayRemoving: \a-m ${Me.Song[${intBuffSlot}]}
            /removebuff "${Me.Song[${intSDBuffSlot}]}"
            /delay 2s !${Me.Song[${intBuffSlot}].ID}
        }
    /next intBuffSlot
    /deletevar intBuffSlot
    /deletevar intSDBuffSlot
/return
```

**Comment by brainiac** [comment]
Can you do the following for me:

1. Open up the MQ2Nav tools window (/nav ui)
2. Go to the Debug Tools window
3. expand the door handler debug section
4. Adjust the trigger distance to something small (smaller than your distance to the switch, so it doesn't click)
5. stand near the switch that is being activated, and click Force enabled
6. The switch should be at the top of the list. Note its id and name.
7. Go up to Objects, and expand the section
8. Expand door objects
9. Look for the object with the matching id and name
10. Expand the object and capture all the information in a screenshot and paste it here for me.

**Comment by BDeakins** [comment]
![image](https://user-images.githubusercontent.com/36932988/65046187-be39ff00-d925-11e9-9e6f-90e6bd00baa6.png)

**Comment by BDeakins** [comment]
![image](https://user-images.githubusercontent.com/36932988/65047300-e0348100-d927-11e9-9ca8-84027a86a0c9.png)
